services:
  - type: web
    name: susetec-store
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    preDeployCommand: flask db upgrade   # <-- makes sure migrations run
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app:create_app
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      # inject connection string from the database below
      - key: DATABASE_URL
        fromDatabase:
          name: store-db                # <-- must match your DB name in Render dashboard
          property: connectionString
    healthCheckPath: /

databases:
  - name: store-db
    plan: free
    databaseName: susetec
    user: susetec
